version: '3.9'

services:
  simulation:
    image: python:3.11-slim
    container_name: bee_simulation
    working_dir: /app
    volumes:
      - ~/repos/sim-one:/app
    environment:
      - TIME_MULTIPLIER=1.0
      - DISPLAY=${DISPLAY}  # For X11 forwarding
    command: >
      bash -c "pip install pygame numpy &&
      python main.py"